=== cloudogu/ces-exporter/docs/system-info.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "fqdn": {
      "type": "string"
    },
    "isMultinode": {
      "type": "boolean"
    },
    "dogus": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "version": {
              "type": "string"
            },
            "volume": {
              "type": "object",
              "properties": {
                "path": {
                  "type": "string"
                },
                "sizeInBytes": {
                  "type": "integer"
                }
              },
              "required": [
                "path",
                "sizeInBytes"
              ]
            }
          },
          "required": [
            "name",
            "version",
            "volume"
          ]
        }
      ]
    },
    "packages": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "version": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "version"
          ]
        }
      ]
    },
    "components": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "version": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "version"
          ]
        }
      ]
    }
  },
  "required": [
    "fqdn",
    "isMultinode",
    "dogus"
  ]
}

=== cloudogu/ces-exporter/docs/system-info.json
{
  "fqdn": "192.168.56.2",
  "isMultinode": false,
  "dogus": [
    {
      "name": "premium/cas",
      "version": "7.0.8-10",
      "volume": {
        "path": "/data/cas",
        "sizeInBytes": 18885
      }
    },
    {
      "name": "official/sonar",
      "version": "9.9.7-1",
      "volume": {
        "path": "/data/sonar",
        "sizeInBytes": 352950770
      }
    }
  ],
  "packages": [
    {
      "name": "backup-watcher",
      "version": "1.3.0"
    },
    {
      "name": "ces-setup",
      "version": "1.10.5"
    },
    {
      "name": "ces-commons",
      "version": "1.4.0"
    }
  ],
  "components": [
    {
      "name": "k8s/k8s-dogu-operator",
      "version": "1.0.1"
    },
    {
      "name": "k8s/k8s-dogu-operator-crd",
      "version": "1.0.1"
    }
  ]
}
